name: Build Star Mobile APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Gradle
        run: |
          echo "=== ROOT FILES ==="
          ls -la
          echo "=== GRADLE TASKS ==="
          gradle tasks --all

      - name: Build APK
        run: gradle :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Star-Mobile-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
